### ISSUE TITLE
关于验证token

### ISSUE THREAD

**Issue by Archie2035** [leizongmin/book-nodejs-in-action-season-2#3]
> 那么在验证access_token时，我们可以先取出其中的时间戳来判断是否过期。

我觉得这样做是没有必要的，因为每次使用api时都要检查token是否正确，而超时的token毕竟频率比较低，而这样每次都有额外的检查是否超时感觉是增加了计算量，并没有缓解数据库的压力。

**Comment by leizongmin** [comment]
这只是举个例子，是否有必要可能要看实际情况。
